### ISSUE TITLE
Detect and report on AirTags / FindMy devices

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#1133]
## TODO

- [ ] Decode/Translate `device_type`
- [ ] Fix or remove `battery_level_string`. It's definitely not correct currently.
- [x] Report in UI

**Comment by lennartkoopmann** [comment]
Not showing/using all parameters for now because they seem to be very unreliable.
