### ISSUE TITLE
802.11 Packet Capture

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#815]
- [x] Make interfaces configurable in config file
- [x] Confirm metrics are working
- [x] Set up monitor interfaces reliably
- [x] Channel Hopping
  - [x] Show supported channels and channel hopping of tap
  - [ ] ~~Allow to limit bands: 2.4/5 Ghz~~
- [x] OUI support (on node)
- [x] Header Parsing
  - [x] Data Rate
  - [x] Channel Number
  - [x] Frequency 
  - [x] Signal strength (dBm)
  - [x] Bound checks in variable header parsing
  - [x] Catch any errors/panics in thread to avoid exit
- [x] Parse frame type and subtype 
- [ ] ~~Parse all management frame types~~ -> Moved to #822
  - [ ] Association Request
  - [ ] Reassociation Request
  - [x] Probe Request
  - [ ] Timing Advertisement
  - [x] Beacon 
  - [ ] Disassocation
  - [x] Deauthentication
  - [ ] Authentication
  - [ ] Action
  - [ ] Association Response
  - [ ] Reassociation Response
  - [x] Probe Response
- [ ] ~~High-level parse all frame types, at least identify and count the weird ones~~
- [x] Fingerprinting
- [x] Checksum validations
- [ ] ~~Use Netlink to enable interfaces and monitor mode~~ -> Moved to #823
  - [ ] Remove `iw`/`if` configs 
- [ ] ~~Work with lost/reconnected interfaces and re-connect~~ -> Moved to #824
  - [ ] if up/down
  - [ ] monitor lost
  - [ ] physically disconnected  
- [ ] ~~DB retention cleaning~~ -> Moved to #825
- [x] Stabilize Netlink channel hopping
