### ISSUE TITLE
802.11 Analysis

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#816]
- [x] Go through v1.0 features/alerts and add here
- [x] ~~Overview of what BSSID exchanges how much data with what BSSID~~ -> #826
  - [ ] Data
  - [ ] Retries
  - [ ] Frame Types
  - [ ] Show this globally, too. (Make it filterable)
- [ ] ~~New alerts~~ -> #827
  - [ ] Location / Triangulation
  - [ ] Beacon Timestamp wildly different (consider restarts)
  - [ ] Beacon capabilities different
  - [ ] Beacon interval different
  - [ ] Access points advertising with probe responses only
  - [ ] Infrastructure type different
  - [ ] Any ad-hoc network seen
  - [ ] Unusual amounts of retries between two stations
  - [ ] Unusual amount of probe requests from single client
  - [ ] Delta between signal strengths of SSIDs per BSSID 
- [ ] ~~Traps (better name?)~~ -> #828
- [x] Show BSSID hidden SSID frames
- [x] Show channels in use overview
- [x] Include data frame intel in client data
- [ ] ~~Disable tap selector when not requested~~ -> #829
- [x] Identify Clients
  - [x] Parse relevant frames into BSSID clients table
    - [x] FrameSubType::Data
    - [x] FrameSubType::QosData
    - [x] FrameSubType::QosDataCfAck
    - [x] FrameSubType::QosDataCfPoll
    - [x] FrameSubType::QosDataCfAckCfPoll
  - [x] Capture statistics
    - [x] Frames
    - [x] Bytes
    - [x] Retries
- [ ] ~~Access Point Table~~ -> #830
  - [x] Show OUI
  - [x] Show security protocols 
  - [ ] Sorting
  - [ ] Highlight/Warn when critical/relevant params have multiple values.
  - [x] Show how many frames were received by BSSIDs and SSIDs during time frame
  - [x] Test tap selector works 
  - [ ] Show info when multiple taps selected (average/aggregated values)
  - [x] Auto-refresh toggle
  - [x] Show network type (infra/adhoc etc)
  - [x] Stop auto-update when auto-refresh is on / restart when no details and was enabled before ("pause")?
- [ ] ~~BSSID Details page~~ -> #831
  - [x] List rates
  - [x] Show how many advertisements happened through beacons, how many through probe-resp
  - [ ] Highlight/Warn when critical/relevant params have multiple values.
  - [ ] Show throughput/frames, let user filter by frame type
  - [ ] Handle situation where network has not been seen in more than 15 minutes. Allow to search over all data.
  - [x] Show data is aggregated over last X minutes
- [x] Number of BSSIDs, SSIDs seen
- [ ] ~~Number of frames seen, let user filter by frame type~~ -> Moved to task
- [ ] ~~Deauth analysis~~ -> 832
