### ISSUE TITLE
Implement additional 802.11 alerts / detection

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#875]
(From #827)

- [ ] Similar looking SSID detected -> #976
- [ ] Beacon rate anomaly -> #957
- [ ] Beacon Timestamp wildly different (consider restarts) -> #977
- [ ] Beacon interval different -> #977
