### ISSUE TITLE
META: Documentation and release notes for alpha.4

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#908]
## Important Changes

* Track detection alert is now calculated for each tap individually

## Breaking Changes

* New tap config file for 2G, 5G, 6G

# High Level Changes

* WiFi 6e Support
* Channel List Template Generator
* Netlink Improvements
* Deauthentication Overview
* Custom WiFi Bandits
* Configurable Signal Track Detector Config
* Smaller Improvements
  * Show MFA TOTP URL together with QR code
  * Organization events & actions now in top level navigation
  *  Alert subscriptions now showing as part of action subscription list
  * Plugins POM on Maven Central
  * Bugfixes
 
## Documentation

- [x] Signal track tuning #903
  - [x] How to change, when to change, what parameters mean
  - [x] Signal track monitoring is running for each tap now
- [x] Custom bandits #902
- [x] Update tap config file for new channel syntax
